language: go

env:
  - GO111MODULE=on

install: true

before_install:
  - export PATH=$HOME/gopath/bin:$PATH
  # install gometalinter
  - curl -L https://git.io/vp6lP | sh

script:
  - PATH=$PWD/bin:$PATH gometalinter ./...
  - go test -race -cover ./...

matrix:
  allow_failures:
    - go: tip
    - go: "1.7.x"
    - go: "1.8.x"
    - go: "1.9.x"
    - go: "1.10.x"
  include:
  - go: "1.7.x"
    script:  go test -v ./...
  - go: "1.8.x"
    script:  go test -v ./...
  - go: "1.9.x"
    script:  go test -v ./...
  - go: "1.10.x"
    script:  go test -v ./...
  - go: "1.11.x"
    script: go test -v -mod=vendor ./...
  - go: "1.12.x"
    script: go test -v -mod=vendor ./...
  - go: "1.13.x"
    script: go test -v -mod=vendor ./...
  - go: "tip"
    script: go test -v -mod=vendor ./...
#poweron support added 
  - go: "1.7.x"
    arch : ppc64le
    script:  go test -v ./...
  - go: "1.8.x"
    arch : ppc64le
    script:  go test -v ./...
  - go: "1.9.x"
    arch : ppc64le
    script:  go test -v ./...
  - go: "1.10.x"
    arch : ppc64le
    script:  go test -v ./...
  - go: "1.11.x"
    arch : ppc64le
    script: go test -v -mod=vendor ./...
  - go: "1.12.x"
    arch : ppc64le
    script: go test -v -mod=vendor ./...
  - go: "1.13.x"
    arch : ppc64le
    script: go test -v -mod=vendor ./...
  - go: "tip"
    arch : ppc64le
    script: go test -v -mod=vendor ./...
git:
  depth: 10
